### ISSUE TITLE
does not work on raspberry pi

### ISSUE THREAD

**Issue by SG-aniki** [joeljogy/Getting-GeoLocation#1]
install the latest chrome drivers from ubtuntu site, following reddit.
https://www.reddit.com/r/selenium/comments/7341wt/success_how_to_run_selenium_chrome_webdriver_on/

Traceback (most recent call last):
  File "getlocation.py", line 20, in <module>
    print(getLocation())
  File "getlocation.py", line 9, in getLocation
    driver = webdriver.Chrome**(executable_path = '/usr/lib/chromium-browser/chromedriver')**
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.35 (0),platform=Linux 4.19.66-v7l+ armv7l)

**Comment by SG-aniki** [comment]
Anyone?

**Comment by SG-aniki** [comment]
solved, 

https://stackoverflow.com/questions/22476112/using-chromedriver-with-selenium-python-ubuntu

Installed the chromium-chromedriver:

sudo apt-get install chromium-chromedriver
Adding the path to the selenium line:

driver = webdriver.Chrome("/usr/lib/chromium-browser/chromedriver")
